# Generated by Django 5.0.1 on 2024-02-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
