# Generated by Django 5.0.1 on 2024-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneruser',
            name='occupation',
            field=models.IntegerField(choices=[(0, 'Employed'), (1, 'Business'), (2, 'Unemployed')], default=0),
        ),
    ]
