# Generated by Django 5.0.1 on 2024-03-03 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allowed_lease_people',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='house_build_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='mainapp.owneruser'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image1',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image2',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image3',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image4',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image5',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
