# Generated by Django 5.0.1 on 2024-03-03 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allowed_lease_people',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='house_build_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='mainapp.owneruser'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image1',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image2',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image3',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image4',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_image5',
            field=models.FileField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('lease_agreement', 'Lease Agreement'), ('utility_bill', 'Utility Bill'), ('building_approval_plan', 'Building Approval Plan'), ('occupancy_certificate', 'Occupancy Certificate')], max_length=50)),
                ('document_image', models.ImageField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('verification_status', models.BooleanField(default=False, help_text='True if the document has been verified')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mainapp.property')),
            ],
        ),
    ]
