# Generated by Django 5.0.1 on 2024-03-18 10:04

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainapp', '0013_remove_owneruser_identification_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='institute',
            name='city',
            field=models.TextField(default='Windsor'),
        ),
        migrations.AddField(
            model_name='institute',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='state',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='AB', max_length=130),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('mobile_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='AB', max_length=130)),
                ('city', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=7)),
                ('offer_letter', models.ImageField(blank=True, null=True, upload_to='documents/offer_letters/')),
                ('country', models.CharField(max_length=255)),
                ('identification', models.ImageField(blank=True, null=True, upload_to='documents/owner/identifications/')),
                ('occupation', models.IntegerField(blank=True, choices=[(0, 'Employed'), (1, 'Business'), (2, 'Unemployed')], default=0, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.institute')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bidding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.appuser'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.appuser'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='mainapp.appuser'),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('lease_agreement', 'Lease Agreement'), ('utility_bill', 'Utility Bill'), ('building_approval_plan', 'Building Approval Plan'), ('occupancy_certificate', 'Occupancy Certificate')], max_length=50)),
                ('document_image', models.ImageField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('verification_status', models.BooleanField(default=False, help_text='True if the document has been verified')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mainapp.property')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='OwnerUser',
        ),
    ]
