# Generated by Django 5.0.1 on 2024-03-20 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_studentuser_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='zip_code',
            field=models.TextField(default='N9B 2T6'),
        ),
        migrations.AddField(
            model_name='property',
            name='bidding_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='institute',
            name='country',
            field=models.TextField(blank=True, default='Canada', null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='ON', max_length=130),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image5',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
    ]
