# Generated by Django 5.0.1 on 2024-03-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_propertytype_institute_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='proofidentity',
            field=models.IntegerField(blank=True, choices=[(0, 'Passport'), (1, 'Driving License'), (2, 'Photo ID')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='rental_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner/rental_license/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='country_code',
            field=models.IntegerField(blank=True, choices=[(1, '+1   (Canada)'), (44, '+44  (UK)'), (91, '+91  (India)'), (61, '+61  (Australia)')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner/identifications/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/offer_letters/'),
        ),
    ]
