# Generated by Django 5.0.1 on 2024-03-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_propertytype_institute_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner/identifications/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/offer_letters/'),
        ),
    ]
