# Generated by Django 5.0.1 on 2024-03-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_appuser_identification_and_more'),
        ('mainapp', '0016_appuser_proofidentity_appuser_rental_license_and_more'),
    ]

    operations = [
    ]
