# Generated by Django 5.0.1 on 2024-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_image1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image5',
            field=models.ImageField(blank=True, null=True, upload_to='documents/property_images/'),
        ),
    ]
