# Generated by Django 5.0.1 on 2024-03-20 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_property_prop_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expire_post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
