# Generated by Django 5.0.1 on 2024-03-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_property_expire_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='expire_post_date',
            new_name='bidding_end_date',
        ),
    ]
